// Generated by CoffeeScript 1.10.0
(function() {
  var timeStampHandler;

  timeStampHandler = function(req, res) {
    var date, result, str;
    str = req.params.str;
    if (!isNaN(str)) {
      str = Number(str);
    }
    date = new Date(str);
    if (isNaN(Number(date))) {
      result = {
        unix: null,
        natural: null
      };
    } else {
      result = {
        unix: Number(date),
        natural: date.toLocaleDateString()
      };
    }
    return res.send(JSON.stringify(result));
  };

  module.exports = timeStampHandler;

}).call(this);
